services:
  graphhopper:
    build:
      context: graphhopper
      dockerfile: Dockerfile
      args:
        GH_VERSION: "11.0"

    container_name: graphhopper

    environment:
      - JAVA_OPTS=-Xmx8g -Xms2g # Max memory : 8GB, initial memory: 2GB

    volumes:
      - ./graphhopper/osm/pays-de-la-loire-latest.osm.pbf:/data/map.osm.pbf:ro
      - ./graphhopper/config.yml:/config.yml:ro
      - ./graphhopper/custom_models:/data/custom_models:ro
      - gh_data:/data/graphhopper
      - srtm_cache:/data/srtm_cache

    command: ["/config.yml"]

    ports:
      - "8989:8989"

    develop:
      watch:
        - path: ./graphhopper/config.yml
          action: sync+restart
          target: /config.yml
        - path: ./graphhopper/custom_models
          action: sync+restart
          target: /data/custom_models

  nominatim:
    image: mediagis/nominatim:5.2

    container_name: nominatim

    ports:
      - "8991:8080"

    volumes:
      - ./graphhopper/osm/pays-de-la-loire-latest.osm.pbf:/osm/map.osm.pbf:ro
      - nominatim_data:/var/lib/postgresql/16/main

    environment:
      - PBF_PATH=/osm/map.osm.pbf
      - THREADS=8

volumes:
  gh_data:
  srtm_cache:
  nominatim_data: