<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AstreaEngine.Playground</AssemblyName>
    <RootNamespace>AstreaEngine.Playground</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\lib\AstreaEngine.csproj" />
  </ItemGroup>

</Project>
